# This is a basic workflow to help you get started with Actions

name: fork

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  fork

jobs:
  say_hello:
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo "Hello forker!"
